### ISSUE TITLE
[💻Code] 1주차_9p_인스턴스 통제

### ISSUE THREAD

**Issue by Jyoungjo** [code-appender/effective-java#10]
### ❓이런 코드가 필요해요.

>
해당 페이지에서 반복되는 요청에 같은 객체를 반환하는 식으로 인스턴스의 통제가 이루어진다고 하는데 해당 부분에 예시 코드 같은게 있을까요?

**Comment by dlrjs2360** [comment]
## 정적 팩토리 메서드의 인스턴스 통제

반복되는 요청에 같은 객체를 반환한다는 말이 어떤 것일까요? 이는 미리 캐싱된 객체 (static으로 선언되어 메모리에 적재된 객체)를 반환한다는 의미일 수 있고 단순한 String 문자열만 반환한다는 말일 수 있습니다.

그렇다면 인스턴스의 통제가 이루어진다는 말은 무엇을 의미할까요? 이 부분이 조금 어려울 수 있는데 제가 이해한 내용은 다음과 같습니다.

정적 팩토리 메서드를 사용해서 반환할 객체는 이미 생성되어 있을 수도, 생성되어 있지 않을 수도 있습니다. 이 말은 메서드 호출 시점에 인스턴스가 생성될 수도 있고, 이미 생성된 인스턴스를 가져올 수도 있다는 것입니다. 이런 식으로 인스턴스의 생성 시점, 종류를 통제할 수 있다는 말을 의미합니다.

또한 생성자를 제공하지 않고 정적 팩토리 메서드만 제공하는 클래스가 있을 수도 있습니다. private 생성자를 선언해놓으면 외부에서 생성자를 호출하여 인스턴스를 생성할 수 없을 것입니다. 하지만 정적 팩토리 메서드는 사용할 수 있죠. 이 정적 팩토리 메서드가 어떤 인스턴스, 객체를 반환할 지는 사용자의 마음입니다. 불변값(final)을 반환하고 setter를 제거함으로써 멀티 스레드 환경에서 안정적인 클래스를 만들 수도 있습니다.

코드로 표현한다면 다음과 같은 클래스가 인스턴스를 통제하는 클래스라고 볼 수 있습니다. 아주 표본적인 싱글톤이라고 볼 수 있습니다.
```java

public class Singleton {
    private static final Singleton INSTANCE = new Singleton();

    private Singleton() {}

    public static Singleton getInstance() {
        return INSTANCE;
    }

}
```

이 예시를 보면 INSTANCE라는 변수는 클래스 로드 시점에 생성되어 프로그램이 종료될 때까지 메모리에 적재되어 있겠구나 라는 것을 알 수 있습니다.

또한, getInstance() 라는 정적 팩토리 메서드는 항상 INSTANCE만 반환함으로써 늘 같은 객체만 사용하고 있고 이 INSTANCE를 수정할 수 있는 메서드는 보이지 않기 때문에 불변 클래스라고 할 수 있습니다.

마지막으로 생성자에 private 키워드를 사용하면서 외부에서 생성자를 통해 인스턴스화를 할 수 없는 클래스라고 볼 수 있겠습니다.

---

이 부분은 책이 너무 어려운 말로 적어놔서 이해하는 데에 오랜 시간이 걸렸습니다...
