### ISSUE TITLE
[💡Question] 1주차_p24_제네릭 싱글턴 팩터리

### ISSUE THREAD

**Issue by juhee77** [code-appender/effective-java#2]
### ❓이런 내용이 궁금해요.

>

<img width="493" alt="image" src="https://github.com/code-appender/effective-java/assets/51548333/9f60171c-419d-4233-991a-642119e371f2">

제네릭 싱글턴 팩터리로 만들 수 있다가 왜 장점인가용? 
그리고 제네릭 싱글턴 패턴에 알고 싶습니다

**Comment by dlrjs2360** [comment]
## 재네릭 싱글톤 패턴이란
재네릭 싱글톤 패턴은 제네릭으로 타입 설정이 가능한 인스턴스를 만들어두고 반환 시에 제네릭으로 받은 타입을 이용해서 타입을 결정짓는 것입니다.

```java
public class GenericFactoryMethod {
public static final Set EMPTY_SET = new HashSet();

    public static final <T> Set<T> emptySet() {
        return (Set<T>) EMPTY_SET;
    }
}
```
이런 방식을 사용하면 여러 타입으로 내부 객체를 받을 수 있어서 유연성이 확대된다는 장점이 있습니다.

## 예시코드
```java
public void genericTest() {
    Set<String> set = GenericFactoryMethod.emptySet();
    Set<Integer> set2 = GenericFactoryMethod.emptySet();
    Set<Elvis> set3 = GenericFactoryMethod.emptySet();

    set.add("ab");
    set2.add(123);
    set3.add(Elvis.INSTANCE);

    String s = set.toString();
    System.out.println("s = " + s);
}
```
