### ISSUE TITLE
[💡Question] 1주차_p32_유한상태머신

### ISSUE THREAD

**Issue by juhee77** [code-appender/effective-java#5]
### ❓이런 내용이 궁금해요.

>
<img width="451" alt="image" src="https://github.com/code-appender/effective-java/assets/51548333/f0dc672c-d498-4cbc-9a02-2dbcefe30fd2">

혹시 여기서 유한 상태 머신이란게 뭘까요?? 그리고 왜 비싼가용?

**Comment by dlrjs2360** [comment]
## 정규표현식 검증 과정
정규 표현식에 대한 문자열 매칭을 수행하는 과정은 다음과 같습니다:
1. Pattern.compile(String regex) 메서드를 호출하여 정규 표현식을 컴파일하고 Pattern 객체를 생성합니다. 이 과정에서 정규 표현식에 해당하는 FSM이 내부적으로 생성됩니다.
2. Pattern.matcher(String input) 메서드를 호출하여 Matcher 객체를 생성합니다. Matcher 객체는 FSM을 사용하여 입력 문자열에 대해 매칭을 수행합니다.
3. Matcher 객체의 find(), matches(), group(), start(), end() 등의 메서드를 사용하여 매칭 결과를 확인하고 처리합니다.

## Pattern 인스턴스의 생성비용이 비싼 이유
정규 표현식을 컴퓨터가 이해하고 처리할 수 있는 데이터 구조로 변환하는 과정에서 먼저 파싱되어 토큰으로 분리되고, 이 토큰들은 다시 FSM으로 변환됩니다. 이 때, FSM이 생성비용이 높아서 Pattern 인스턴스도 생성 비용이 비싼 것입니다.

## 유한 상태 머신(Finite State Machine, FSM)
유한 상태 머신(FSM)은 상태와 상태 간의 전이를 정의하는 계산 모델입니다. FSM은 일련의 상태와 이 상태 간의 전이를 정의하며, 각 전이는 특정 조건을 만족하면 발생합니다. FSM은 문자열 처리, 프로토콜 설계, 텍스트 분석 등 다양한 분야에서 사용됩니다.

상태 전이를 좀 더 쉽게 이해하기 위해, '신호등'을 예로 들어보겠습니다. 신호등은 '빨간불', '녹색불', '노란불'의 세 가지 상태를 가지며, 이러한 상태는 시간이 지나면서 순환적으로 변화합니다.
'빨간불' 상태에서 일정 시간이 지나면 '녹색불' 상태로 전이합니다.
'녹색불' 상태에서 일정 시간이 지나면 '노란불' 상태로 전이합니다.
'노란불' 상태에서 일정 시간이 지나면 다시 '빨간불' 상태로 전이합니다.

-> 자세하게 들어가면 너무 어려운 것 같습니다..
